stages:
  - lint
  - security
  - test
#linter flakeb
lint_job:
  stage: lint
  image: python:3.12
  before_script:
    - pip install flake8
  script:
    - echo "ejecutando flake8"
    - flake8
#analisis
security_job:
  stage: security
  image: python 3.12
  before_script:
    - pip install bandit
  script:
    - echo "ejecutando analisis de seguridad bandit" 
    - bandit -r . --skip B101  
